AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Resources:

    RootRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
                  - states.amazonaws.com
                  - ecs.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        RoleName: 'ExampleRole'
        Policies:
          - PolicyName: ExamplePolicyRoot
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: '*'
                  Resource: '*'
    # RootInstanceProfile:
    #   Type: 'AWS::IAM::InstanceProfile'
    #   Properties:
    #     Path: /
    #     Roles:
    #       - !Ref RootRole